
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.JOptionPane;
import javax.swing.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hailo
 */

public class client extends javax.swing.JFrame {
private Socket socket;
private BufferedReader reader;
private PrintWriter writer;
private Thread clientThread;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(client.class.getName());

    /**
     * Creates new form client
     */
    public client() {
        initComponents();
        hienthinoinoidung.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noidung = new javax.swing.JLabel();
        connectsever = new javax.swing.JButton();
        tinnhan1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        tinnhan = new javax.swing.JLabel();
        send = new javax.swing.JButton();
        nhapport = new javax.swing.JTextField();
        nhaptinnhan = new javax.swing.JTextField();
        port = new javax.swing.JLabel();
        disconnectsever = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hienthinoinoidung = new javax.swing.JTextArea();
        disconnect = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        nhapidsever = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        send1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noidung.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        noidung.setForeground(new java.awt.Color(255, 255, 255));
        noidung.setText("Nội Dung ");
        getContentPane().add(noidung, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        connectsever.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-off-24-2.png"))); // NOI18N
        connectsever.setText("kết nối");
        connectsever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectseverActionPerformed(evt);
            }
        });
        getContentPane().add(connectsever, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 100, 20));

        tinnhan1.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        tinnhan1.setForeground(new java.awt.Color(255, 255, 255));
        tinnhan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-talk-48.png"))); // NOI18N
        tinnhan1.setText("Disscord mess");
        getContentPane().add(tinnhan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 50));

        id.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("ID");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        tinnhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-customer-30.png"))); // NOI18N
        getContentPane().add(tinnhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-arrow-50.png"))); // NOI18N
        send.setText("Send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        getContentPane().add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 110, 40));
        getContentPane().add(nhapport, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 200, -1));

        nhaptinnhan.setText("Nhập Tin Nhắn");
        nhaptinnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhaptinnhanActionPerformed(evt);
            }
        });
        getContentPane().add(nhaptinnhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 450, 70));

        port.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        port.setForeground(new java.awt.Color(255, 255, 255));
        port.setText("Port");
        getContentPane().add(port, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        disconnectsever.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-off-32.png"))); // NOI18N
        disconnectsever.setText("đóng sever");
        disconnectsever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectseverActionPerformed(evt);
            }
        });
        getContentPane().add(disconnectsever, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 100, 20));

        hienthinoinoidung.setColumns(20);
        hienthinoinoidung.setRows(5);
        hienthinoinoidung.setText("\n");
        jScrollPane1.setViewportView(hienthinoinoidung);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 640, 190));

        disconnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-no-50.png"))); // NOI18N
        disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectActionPerformed(evt);
            }
        });
        getContentPane().add(disconnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 0, 40, 30));

        btnClear.setText("Xóa tin nhắn");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 100, -1));

        btnEdit.setText("sửa tin nhắn");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 100, -1));
        getContentPane().add(nhapidsever, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        jLabel1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 470));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 430));

        send1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-arrow-50.png"))); // NOI18N
        send1.setText("Send");
        send1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send1ActionPerformed(evt);
            }
        });
        getContentPane().add(send1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nhaptinnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhaptinnhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhaptinnhanActionPerformed

    private void connectseverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectseverActionPerformed
        // TODO add your handling code here:
         String host = nhapidsever.getText().trim();
    int portNumber;

    try {
        portNumber = Integer.parseInt(nhapport.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Port phải là số!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        socket = new Socket(host, portNumber);
        reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
        writer = new PrintWriter(socket.getOutputStream(), true);
        hienthinoinoidung.append("✅ Đã kết nối đến server " + host + ":" + portNumber + "\n");

        // Tạo luồng đọc tin nhắn từ server
      clientThread = new Thread(() -> {
    try {
        String msg;
        while ((msg = reader.readLine()) != null) {
            String finalMsg = msg;
            SwingUtilities.invokeLater(() -> {
                // Nếu tin không phải của chính mình gửi thì mới hiện là "Bạn"
                if (!finalMsg.startsWith("🧑‍💻 Tôi:")) {
                    hienthinoinoidung.append("💬 Bạn: " + finalMsg + "\n");
                }
            });
        }
    } catch (IOException e) {
        SwingUtilities.invokeLater(() -> 
            hienthinoinoidung.append("⚠️ Mất kết nối với server.\n")
        );
    }
});
clientThread.start();

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Không thể kết nối server!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_connectseverActionPerformed

    private void disconnectseverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectseverActionPerformed
        // TODO add your handling code here:
        try {
        if (socket != null && !socket.isClosed()) {
            socket.close();
            hienthinoinoidung.append("❌ Đã ngắt kết nối server.\n");
        }
    } catch (IOException e) {
        hienthinoinoidung.append("⚠️ Lỗi khi ngắt kết nối.\n");
    }
        
    }//GEN-LAST:event_disconnectseverActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
         if (writer == null) {
        JOptionPane.showMessageDialog(this, "Chưa kết nối server!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return;
    }
    String msg = nhaptinnhan.getText().trim();
    if (!msg.isEmpty()) {
        writer.println(msg);
        hienthinoinoidung.append("🧑‍💻 Tôi: " + msg + "\n");
        nhaptinnhan.setText("");
    }
    }//GEN-LAST:event_sendActionPerformed

    private void disconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectActionPerformed
        // TODO add your handling code here:
           this.dispose();
    }//GEN-LAST:event_disconnectActionPerformed

    private void send1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_send1ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       // Nếu người dùng bôi đen một đoạn tin nhắn → xóa đoạn đó
    int start = hienthinoinoidung.getSelectionStart();
    int end = hienthinoinoidung.getSelectionEnd();
    
    if (start != end) {
        // Xóa phần được bôi đen
        hienthinoinoidung.replaceRange("", start, end);
    } else {
        // Nếu không bôi đen, xóa cả dòng nơi con trỏ đang đứng
        try {
            int caretPos = hienthinoinoidung.getCaretPosition(); // vị trí con trỏ
            int startLine = hienthinoinoidung.getLineStartOffset(
                hienthinoinoidung.getLineOfOffset(caretPos)
            );
            int endLine = hienthinoinoidung.getLineEndOffset(
                hienthinoinoidung.getLineOfOffset(caretPos)
            );
            hienthinoinoidung.replaceRange("", startLine, endLine);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
 try {
        String selectedText = hienthinoinoidung.getSelectedText();

        if (selectedText == null || selectedText.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng tô (bôi đen) dòng muốn sửa trước!");
            return;
        }

        // Hiển thị hộp thoại nhập nội dung mới
        String newText = JOptionPane.showInputDialog(this, "Nhập nội dung mới:", selectedText);
        if (newText == null || newText.trim().isEmpty()) {
            return; // Người dùng bấm Cancel hoặc để trống
        }

        // Lấy toàn bộ nội dung hiện tại
        String fullText = hienthinoinoidung.getText();

        // Thay thế phần được chọn bằng nội dung mới
        int start = hienthinoinoidung.getSelectionStart();
        int end = hienthinoinoidung.getSelectionEnd();

        String updatedText = fullText.substring(0, start)
                + newText
                + fullText.substring(end);

        // Cập nhật lại JTextArea
        hienthinoinoidung.setText(updatedText);

        JOptionPane.showMessageDialog(this, "Đã sửa tin nhắn thành công!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi sửa tin nhắn: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new client().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton connectsever;
    private javax.swing.JButton disconnect;
    private javax.swing.JButton disconnectsever;
    private javax.swing.JTextArea hienthinoinoidung;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nhapidsever;
    private javax.swing.JTextField nhapport;
    private javax.swing.JTextField nhaptinnhan;
    private javax.swing.JLabel noidung;
    private javax.swing.JLabel port;
    private javax.swing.JButton send;
    private javax.swing.JButton send1;
    private javax.swing.JLabel tinnhan;
    private javax.swing.JLabel tinnhan1;
    // End of variables declaration//GEN-END:variables
}
