/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vominhduc
 */
public class DangNhapfrm extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapfrm
     */
    public DangNhapfrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tilte = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblpasss = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        btndangnhap = new javax.swing.JButton();
        lblcreate = new javax.swing.JLabel();
        lblthongbao = new javax.swing.JLabel();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tilte.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        tilte.setForeground(new java.awt.Color(255, 255, 255));
        tilte.setText("ĐĂNG NHẬP HỆ THỐNG");
        getContentPane().add(tilte, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 40));

        lblusername.setForeground(new java.awt.Color(255, 255, 255));
        lblusername.setText("Tên Đăng Nhập");
        getContentPane().add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lblpasss.setForeground(new java.awt.Color(255, 255, 255));
        lblpasss.setText("Passwword");
        getContentPane().add(lblpasss, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        txtusername.setText("Nhập Tên");
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, -1));

        txtpass.setText("jPasswordField1");
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 180, -1));

        btndangnhap.setText("Đăng Nhập");
        getContentPane().add(btndangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        lblcreate.setForeground(new java.awt.Color(255, 255, 255));
        lblcreate.setText("Tạo acc mới");
        getContentPane().add(lblcreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 160, -1));

        lblthongbao.setForeground(new java.awt.Color(255, 255, 255));
        lblthongbao.setText("<html><center><font color='white'>Sai mật khẩu!<br>Vui lòng thử lại.</font></center></html> ");
        getContentPane().add(lblthongbao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        getContentPane().add(lblbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndangnhap;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lblcreate;
    private javax.swing.JLabel lblpasss;
    private javax.swing.JLabel lblthongbao;
    private javax.swing.JLabel lblusername;
    private javax.swing.JLabel tilte;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
