
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hailo
 */

public class client extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(client.class.getName());

    /**
     * Creates new form client
     */
    public client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noidung = new javax.swing.JLabel();
        connectsever = new javax.swing.JButton();
        tinnhan1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        tinnhan = new javax.swing.JLabel();
        send = new javax.swing.JButton();
        nhapport = new javax.swing.JTextField();
        nhaptinnhan = new javax.swing.JTextField();
        port = new javax.swing.JLabel();
        disconnectsever = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hienthinoinoidung = new javax.swing.JTextArea();
        disconnect = new javax.swing.JButton();
        nhapidsever = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noidung.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        noidung.setForeground(new java.awt.Color(255, 255, 255));
        noidung.setText("Nội Dung ");
        getContentPane().add(noidung, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        connectsever.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-off-24-2.png"))); // NOI18N
        getContentPane().add(connectsever, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 30, 20));

        tinnhan1.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        tinnhan1.setForeground(new java.awt.Color(255, 255, 255));
        tinnhan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-talk-48.png"))); // NOI18N
        tinnhan1.setText("Disscord mess");
        getContentPane().add(tinnhan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 50));

        id.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("ID");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        tinnhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-customer-30.png"))); // NOI18N
        getContentPane().add(tinnhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-arrow-50.png"))); // NOI18N
        getContentPane().add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 330, 50, 40));
        getContentPane().add(nhapport, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 200, -1));

        nhaptinnhan.setText("Nhập Tin Nhắn");
        nhaptinnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhaptinnhanActionPerformed(evt);
            }
        });
        getContentPane().add(nhaptinnhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 450, 80));

        port.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        port.setForeground(new java.awt.Color(255, 255, 255));
        port.setText("Port");
        getContentPane().add(port, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        disconnectsever.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-off-32.png"))); // NOI18N
        getContentPane().add(disconnectsever, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 30, 20));

        hienthinoinoidung.setColumns(20);
        hienthinoinoidung.setRows(5);
        hienthinoinoidung.setText("\n");
        jScrollPane1.setViewportView(hienthinoinoidung);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 630, 190));

        disconnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-no-50.png"))); // NOI18N
        getContentPane().add(disconnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 0, 40, 30));
        getContentPane().add(nhapidsever, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 732, 592));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nhaptinnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhaptinnhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhaptinnhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new client().setVisible(true));
    }

    private Socket socket;
private BufferedReader reader;
private PrintWriter writer;
private Thread clientThread;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connectsever;
    private javax.swing.JButton disconnect;
    private javax.swing.JButton disconnectsever;
    private javax.swing.JTextArea hienthinoinoidung;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nhapidsever;
    private javax.swing.JTextField nhapport;
    private javax.swing.JTextField nhaptinnhan;
    private javax.swing.JLabel noidung;
    private javax.swing.JLabel port;
    private javax.swing.JButton send;
    private javax.swing.JLabel tinnhan;
    private javax.swing.JLabel tinnhan1;
    // End of variables declaration//GEN-END:variables
}
