/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vominhduc
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitle = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        lblnhaplaipass = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnsave = new javax.swing.JButton();
        lblbacklogin = new javax.swing.JLabel();
        lblthongbao = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        txtpassagain = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitle.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(255, 255, 255));
        lbltitle.setText("Đăng Ký Tài Khoản");
        getContentPane().add(lbltitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 234, -1));

        lblusername.setForeground(new java.awt.Color(255, 255, 255));
        lblusername.setText("Tên Đăng Nhập");
        getContentPane().add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        lblpass.setForeground(new java.awt.Color(255, 255, 255));
        lblpass.setText("Mật Khẩu");
        getContentPane().add(lblpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        lblnhaplaipass.setForeground(new java.awt.Color(255, 255, 255));
        lblnhaplaipass.setText("Nhập Lại Mặt Khẩu");
        getContentPane().add(lblnhaplaipass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sever", "Cilent" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        btnsave.setText("Lưu Dữ Liệu");
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        lblbacklogin.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblbacklogin.setForeground(new java.awt.Color(255, 255, 255));
        lblbacklogin.setText("Trở Về ");
        getContentPane().add(lblbacklogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        lblthongbao.setForeground(new java.awt.Color(255, 255, 255));
        lblthongbao.setText("<html><center><font color='white'>Mật khẩu không hợp lệ!<br>Hãy nhập lại .</font></center></html> ");
        getContentPane().add(lblthongbao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 150, 40));
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 225, -1));

        txtpass.setText("jPasswordField1");
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 139, -1));

        txtpassagain.setText("jPasswordField2");
        getContentPane().add(txtpassagain, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 139, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -60, 780, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblbacklogin;
    private javax.swing.JLabel lblnhaplaipass;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblthongbao;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lblusername;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JPasswordField txtpassagain;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
