
import java.awt.List;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hailo
 */
public class sever extends javax.swing.JFrame {

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(sever.class.getName());

    /**
     * Creates new form sever
     */
    public sever() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        hienthilog = new javax.swing.JTextArea();
        startsever = new javax.swing.JButton();
        Stopsever = new javax.swing.JButton();
        nhapport = new javax.swing.JTextField();
        tinnhan = new javax.swing.JLabel();
        port = new javax.swing.JLabel();
        btnthoat = new javax.swing.JButton();
        anhnen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hienthilog.setColumns(20);
        hienthilog.setRows(5);
        jScrollPane2.setViewportView(hienthilog);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 600, 300));

        startsever.setForeground(new java.awt.Color(51, 51, 255));
        startsever.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-off-32.png"))); // NOI18N
        getContentPane().add(startsever, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 70, 20));

        Stopsever.setForeground(new java.awt.Color(51, 51, 255));
        Stopsever.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-off-24-2.png"))); // NOI18N
        getContentPane().add(Stopsever, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 80, 20));

        nhapport.setText("Nhập port để lắng nghe");
        getContentPane().add(nhapport, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 300, -1));

        tinnhan.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        tinnhan.setForeground(new java.awt.Color(255, 255, 255));
        tinnhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-talk-48.png"))); // NOI18N
        tinnhan.setText("Disscord mess");
        getContentPane().add(tinnhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 50));

        port.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        port.setForeground(new java.awt.Color(255, 255, 255));
        port.setText("Port");
        getContentPane().add(port, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        btnthoat.setForeground(new java.awt.Color(255, 0, 51));
        btnthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-no-50.png"))); // NOI18N
        getContentPane().add(btnthoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 30, 30));

        anhnen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        getContentPane().add(anhnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 422));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new sever().setVisible(true));
    }
private ServerSocket serverSocket;
private Socket clientSocket;
private BufferedReader reader;
private PrintWriter writer;
private Thread serverThread;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Stopsever;
    private javax.swing.JLabel anhnen;
    private javax.swing.JButton btnthoat;
    private javax.swing.JTextArea hienthilog;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nhapport;
    private javax.swing.JLabel port;
    private javax.swing.JButton startsever;
    private javax.swing.JLabel tinnhan;
    // End of variables declaration//GEN-END:variables
}
